// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUbPeXbMxtSdQTEojkrM8u_aQgVy796aE',
    appId: '1:973118704417:web:63b06963bcdfd7de6a0c60',
    messagingSenderId: '973118704417',
    projectId: 'login-8665a',
    authDomain: 'login-8665a.firebaseapp.com',
    storageBucket: 'login-8665a.appspot.com',
    measurementId: 'G-KJX0NMRQD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC3pPiLgv3kzzJwYzEXlBo43hNcEEBoo8',
    appId: '1:973118704417:android:10fa1077409f52066a0c60',
    messagingSenderId: '973118704417',
    projectId: 'login-8665a',
    storageBucket: 'login-8665a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLLiobuisF-27HK7Nz0ws0iYBL5d6hijs',
    appId: '1:973118704417:ios:454ef5ce14b16ed76a0c60',
    messagingSenderId: '973118704417',
    projectId: 'login-8665a',
    storageBucket: 'login-8665a.appspot.com',
    androidClientId: '973118704417-l48qg7uvr2r3ip8hkqlpp4954ulfl7j9.apps.googleusercontent.com',
    iosClientId: '973118704417-hg4gul6m31hs0nlhlk0rurfte8rhk3s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLLiobuisF-27HK7Nz0ws0iYBL5d6hijs',
    appId: '1:973118704417:ios:aee69f1bcc8c3b8e6a0c60',
    messagingSenderId: '973118704417',
    projectId: 'login-8665a',
    storageBucket: 'login-8665a.appspot.com',
    androidClientId: '973118704417-l48qg7uvr2r3ip8hkqlpp4954ulfl7j9.apps.googleusercontent.com',
    iosClientId: '973118704417-v5qn7s8oal4ngphra1sj3cs5thcfscui.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
