// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGGRjWC0KqsI_RVbjQZ4G-rFq3yrZr4oQ',
    appId: '1:523493339721:web:661c083581ca85430f0598',
    messagingSenderId: '523493339721',
    projectId: 'login-3dcb1',
    authDomain: 'login-3dcb1.firebaseapp.com',
    storageBucket: 'login-3dcb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3ZXOq8xcBK0jIN6ewmTQnKiZZiHxl1M',
    appId: '1:523493339721:android:55774077ffbfc4920f0598',
    messagingSenderId: '523493339721',
    projectId: 'login-3dcb1',
    storageBucket: 'login-3dcb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHswIh7VJhEcyYiU28Q2TFh57zolmV2uM',
    appId: '1:523493339721:ios:b48775982d2759bc0f0598',
    messagingSenderId: '523493339721',
    projectId: 'login-3dcb1',
    storageBucket: 'login-3dcb1.appspot.com',
    iosClientId: '523493339721-o9svcn0k980fq65kjjepmf7q5lghf09n.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHswIh7VJhEcyYiU28Q2TFh57zolmV2uM',
    appId: '1:523493339721:ios:9d5901df001d5bfe0f0598',
    messagingSenderId: '523493339721',
    projectId: 'login-3dcb1',
    storageBucket: 'login-3dcb1.appspot.com',
    iosClientId: '523493339721-mg3o176qes8ejqi68r8k4624q5if5sab.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
